# The tournament's config file
DataSource:
  # What type of database do you want to use?
  # Available values: SQLITE, MYSQL.
  backend: SQLITE
  # Database host address
  mySQLHost: localhost
  # Database port
  mySQLPort: '3306'
   # Username to connect to the MySQL database
  mySQLUsername: ''
  # Password to connect to the MySQL database
  mySQLPassword: ''
  # Database Name
  mySQLDatabase: ''

#The plugin's messages language. Available values: en_EN, ru_RU
lang: en_EN

#Broadcast your tournaments
Auto_Broadcast:
  Enable: true # true - enable broadcasting, false - disable.
  Interval: 5 # in minutes
  Message: '&8[&aTournaments&8]&f The {name} will begin in {time} minutes! To join: &e/tournaments join'